import { v2 as cloudinary } from "cloudinary";

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
});

/**
 * ✅ UPLOAD INVOICE PDF TO CLOUDINARY (BUFFER)
 * @param {Buffer} buffer - The PDF buffer generated by Puppeteer
 * @param {string} orderId - The Order ID for naming the file
 * @returns {Promise<Object>} - { secure_url, public_id }
 */
export const uploadInvoicePDF = (buffer, orderId) => {
  return new Promise((resolve, reject) => {
    const uploadStream = cloudinary.uploader.upload_stream(
      {
        resource_type: "raw",            // ✅ Correctly handles non-image files
        folder: "invoices",              // ✅ Organizes in invoices folder
        public_id: `invoice_${orderId}`, // ✅ Custom naming convention
        format: "pdf",                   // ✅ Ensures .pdf extension
        access_mode: "public",           // ✅ Ensures browser can open it directly
      },
      (error, result) => {
        if (error) {
          console.error("Cloudinary Upload Error:", error);
          return reject(error);
        }
        
        // Returns structured object for storage in Order model
        resolve({
          secure_url: result.secure_url,
          public_id: result.public_id,
        });
      }
    );

    uploadStream.end(buffer);
  });
};

/**
 * ✅ LEGACY HELPER
 * Maintains compatibility with previous controller calls
 */
export const uploadInvoiceToCloudinary = async (pdfBuffer, orderId) => {
  const result = await uploadInvoicePDF(pdfBuffer, orderId);
  return result.secure_url;
};

export default cloudinary;